apps/misiones/urls.py
from django.urls import path
from . import views

app_name = 'misiones'

urlpatterns = [
    path('', views.lista_misiones, name='misiones'),
    path('api/misiones/<int:mision_id>/intentos/', views.obtener_intentos_mision, name='obtener_intentos_mision'),
    path('api/misiones/intentos/<int:intento_id>/', views.actualizar_estado_intento, name='actualizar_estado_intento'),
    path('api/misiones/<int:mision_id>/alternativas/', views.obtener_alternativas_mision, name='obtener_alternativas_mision'),
    path('guardar-intento/', views.guardar_intento_mision, name='guardar_intento'),
    path('api/polya/<int:mision_id>/', views.obtener_polya_um, name='obtener_polya_um'),
    path('api/polya/<int:mision_id>/guardar/', views.guardar_polya_um, name='guardar_polya_um'),
    path('api/polya/<int:mision_id>/estudiante/<int:usuario_id>/', views.obtener_polya_um_estudiante, name='obtener_polya_um_estudiante'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from web_project.views import SystemView
from django.conf import settings
from django.conf.urls.static import static
from apps.authentication.views import home_redirect

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", home_redirect, name="home_redirect"),

    # Dashboard urls
    path("welcome/", include("apps.dashboards.urls")),

    # layouts urls
    path("", include("apps.layouts.urls")),

    # Auth urls
    path("", include("apps.authentication.urls")),

    # Misiones urls
    path('misiones/', include('apps.misiones.urls', namespace='misiones')),

    # Biblioteca urls
    path('biblioteca/', include('apps.biblioteca.urls', namespace='biblioteca')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout/partials/menu/vertical/admin_menu.html
{% block admin_menu %}
<aside id="layout-menu" class="layout-menu menu-vertical menu">
  {% if not navbar_full %}
  <div class="app-brand demo">
    <a href="{% url 'index' %}" class="app-brand-link">
      <span class="app-brand-logo demo me-1">
        {% include 'partials/logo.html' %}
      </span>
      <span class="app-brand-text demo menu-text fw-semibold ms-2">{% get_theme_variables 'template_name' %}</span>
    </a>
  </div>
  {% endif %}

  <div class="menu-inner-shadow"></div>

  <ul class="menu-inner py-1"> 
    <li class="menu-item {% if 'gestion-usuarios' in request.path %}active{% endif %}">
      <a href="{% url 'gestion-usuarios' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-user-settings-line"></i>
        <div class="text-truncate">Gestión de Usuarios</div>
      </a>
    </li> 
    <li class="menu-divider"></li>
    <li class="menu-item">
      <a href="{% url 'auth-login-basic' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-logout-box-r-line"></i>
        <div class="text-truncate">Salir</div>
      </a>
    </li>
  </ul>
</aside>
{% endblock %}

templates/layout/partials/menu/vertical/professor_menu.html
{% block professor_menu %}
<aside id="layout-menu" class="layout-menu menu-vertical menu">
  {% if not navbar_full %}
  <div class="app-brand demo">
    <a href="{% url 'index' %}" class="app-brand-link">
      <span class="app-brand-logo demo me-1">
        {% include 'partials/logo.html' %}
      </span>
      <span class="app-brand-text demo menu-text fw-semibold ms-2">{% get_theme_variables 'template_name' %}</span>
    </a>
  </div>
  {% endif %}

  <div class="menu-inner-shadow"></div>

  <ul class="menu-inner py-1"> 
     <li class="menu-item {% if request.resolver_match.url_name == 'misiones' %}active{% endif %}">
      <a href="{% url 'misiones:misiones' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-rocket-line"></i>
        <div class="text-truncate">Misiones</div>
      </a>
    </li>
      <li class="menu-item {% if 'gestion-biblioteca' in request.path %}active{% endif %}">
      <a href="{% url 'gestion-biblioteca' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-book-2-line"></i>
        <div class="text-truncate">Gestión de Biblioteca</div>
      </a>
    </li>
      <li class="menu-item {% if 'reportes-estudiantes' in request.path %}active{% endif %}">
      <a href="{% url 'reportes-estudiantes' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-bar-chart-line"></i>
        <div class="text-truncate">Reportes de Estudiantes</div>
      </a>
    </li>
    <li class="menu-divider"></li>
    <li class="menu-item">
      <a href="{% url 'auth-login-basic' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-logout-box-r-line"></i>
        <div class="text-truncate">Salir</div>
      </a>
    </li>
  </ul>
</aside>
{% endblock %}

templates/layout/partials/menu/vertical/student_menu.html
{% block student_menu %} 


<aside id="layout-menu" class="layout-menu menu-vertical menu">
  {% if not navbar_full %}
  <div class="app-brand demo">
    <a href="{% url 'index' %}" class="app-brand-link">
      <span class="app-brand-logo demo me-1">
        {% include 'partials/logo.html' %}
      </span>
      <span class="app-brand-text demo menu-text fw-semibold ms-2">{% get_theme_variables 'template_name' %}</span>
    </a>
  </div>
  {% endif %}


  <div class="menu-inner-shadow"></div>

  <ul class="menu-inner py-1">
    <li class="menu-item {% if request.resolver_match.url_name == 'index' %}active{% endif %}">
      <a href="{% url 'index' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-home-smile-line"></i>
        <div class="text-truncate">Inicio</div>
      </a>
    </li>
    <li class="menu-item {% if request.resolver_match.url_name == 'opciones_aprendizaje' %}active{% endif %}">
      <a href="{% url 'opciones_aprendizaje' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-lightbulb-flash-line"></i>
        <div class="text-truncate">Biblioteca</div>
      </a>
    </li>
    <li class="menu-item {% if request.resolver_match.url_name == 'misiones' %}active{% endif %}">
      <a href="{% url 'misiones:misiones' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-rocket-line"></i>
        <div class="text-truncate">Misiones</div>
      </a>
    </li>
    <li class="menu-item {% if request.resolver_match.url_name == 'mapa_progreso' %}active{% endif %}">
      <a href="{% url 'mapa_progreso' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-bar-chart-2-line"></i>
        <div class="text-truncate">Mi Mapa de Progreso</div>
      </a>
    </li>
    <li class="menu-divider"></li>
    <li class="menu-item">
      <a href="{% url 'auth-login-basic' %}" class="menu-link">
        <i class="menu-icon icon-base ri ri-logout-box-r-line"></i>
        <div class="text-truncate">Salir</div>
      </a>
    </li>
  </ul>
</aside>
{% endblock %}

templates/layout/partials/menu/vertical/vertical_menu.html
<aside id="layout-menu" class="layout-menu menu-vertical menu">
  {% if not navbar_full %}
  <div class="app-brand demo">
    <a href="{% url 'index' %}" class="app-brand-link">
      <span class="app-brand-logo demo me-1">
        {% include 'partials/logo.html' %}
      </span>
      <span class="app-brand-text demo menu-text fw-semibold ms-2">{% get_theme_variables 'template_name' %}</span>
    </a>
  </div>
  {% endif %}

  {# Menú dinámico basado en el rol del usuario #}
 
    {% if user.rol.tipo == 'Estudiante' %}
      {% include 'layout/partials/menu/vertical/student_menu.html' %}
    {% elif user.rol.tipo == 'Profesor' %}
      {% include 'layout/partials/menu/vertical/professor_menu.html' %}
    {% elif user.rol.tipo == 'Admin' or user.is_superuser %}
      {% include 'layout/partials/menu/vertical/admin_menu.html' %}
  
</aside>